"""init

Revision ID: f89845517850
Revises: 
Create Date: 2026-09-25 23:09:52.531701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89845517850'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('clients', sa.Integer(), nullable=False),
    sa.Column('path', sa.JSON(), nullable=True),
    sa.Column('uptime_s', sa.Integer(), nullable=False),
    sa.Column('tx', sa.Integer(), nullable=False),
    sa.Column('rx', sa.Integer(), nullable=False),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('neighbors', sa.JSON(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index(op.f('ix_nodes_last_seen'), 'nodes', ['last_seen'], unique=False)
    op.create_index(op.f('ix_nodes_status'), 'nodes', ['status'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reply_to', sa.Integer(), nullable=False),
    sa.Column('target_node', sa.Integer(), nullable=True),
    sa.Column('path', sa.JSON(), nullable=True),
    sa.Column('sender', sa.String(length=32), nullable=False),
    sa.Column('text', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msg_id', name='uq_messages_msg_id')
    )
    op.create_index(op.f('ix_messages_msg_id'), 'messages', ['msg_id'], unique=False)
    op.create_index(op.f('ix_messages_reply_to'), 'messages', ['reply_to'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.Integer(), nullable=False),
    sa.Column('path', sa.JSON(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('needs', sa.Integer(), nullable=False),
    sa.Column('gps_lat', sa.Double(), nullable=True),
    sa.Column('gps_lon', sa.Double(), nullable=True),
    sa.Column('gps_accuracy', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acked_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('ai_priority', sa.Integer(), nullable=True),
    sa.Column('ai_category', sa.Integer(), nullable=True),
    sa.Column('ai_summary', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('msg_id', name='uq_reports_msg_id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_msg_id'), 'reports', ['msg_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_msg_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to'), table_name='messages')
    op.drop_index(op.f('ix_messages_msg_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('users')
    op.drop_index(op.f('ix_nodes_status'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_last_seen'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
